# Generated by Django 3.1.14 on 2022-01-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='dissappeared_ad',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
